export const ACHIEVEMENTS = [
  {
    code: 'coffee_breaker',
    nameEn: 'Coffee Breaker',
    nameRu: 'Кофейный отказник',
    descriptionEn: 'First coffee refusal',
    descriptionRu: 'Первый отказ от кофе',
    icon: '☕',
    pointsRequired: null,
  },
  {
    code: 'sugar_free',
    nameEn: 'Sugar Free',
    nameRu: 'Без сахара',
    descriptionEn: '7 days without soda',
    descriptionRu: '7 дней без газировки',
    icon: '🥤',
    pointsRequired: null,
  },
  {
    code: 'smoke_out',
    nameEn: 'Smoke Out',
    nameRu: 'Бросил курить',
    descriptionEn: '14 days streak',
    descriptionRu: '14 дней подряд',
    icon: '🚬',
    pointsRequired: null,
  },
  {
    code: 'budget_ninja',
    nameEn: 'Budget Ninja',
    nameRu: 'Бюджетный ниндзя',
    descriptionEn: 'Saved $40+',
    descriptionRu: 'Накоплено $40+',
    icon: '🥷',
    pointsRequired: 40,
  },
  {
    code: 'momentum',
    nameEn: 'Momentum',
    nameRu: 'Импульс',
    descriptionEn: '21 day streak',
    descriptionRu: '21 день подряд',
    icon: '⚡',
    pointsRequired: null,
  },
  {
    code: 'ref_hero',
    nameEn: 'Ref Hero',
    nameRu: 'Реферальный герой',
    descriptionEn: '3 active referrals',
    descriptionRu: '3 реферала с активностью',
    icon: '🦸',
    pointsRequired: null,
  },
  {
    code: 'consistency_king',
    nameEn: 'Consistency King/Queen',
    nameRu: 'Король/Королева постоянства',
    descriptionEn: '60 day streak',
    descriptionRu: '60 дней подряд',
    icon: '👑',
    pointsRequired: null,
  },
  {
    code: 'iron_will',
    nameEn: 'Iron Will',
    nameRu: 'Железная воля',
    descriptionEn: '30 days without skips',
    descriptionRu: '30 дней без пропусков',
    icon: '🛡️',
    pointsRequired: null,
  },
];